"""
DeepVision Schemas Package
Exports all domain-specific Pydantic data schemas.
"""

from .common import (
    MediaType,
    DetectionVerdict,
    UserRole,
    FeedbackStatus,
    APIError,
    ErrorResponse,
    SuccessResponse,
    PaginationParams,
)
from .detection import (
    DetectionRequest,
    DetectionResult,
    DetectionHistoryItem,
    DetectionHistoryResponse,
    DetectionAnalytics,
)
from .user import (
    UserPublic,
    UserUpdate,
    UserStatistics,
    UserSettings,
    UserSettingsUpdate,
    UserAnalyticsOverview,
    ChartData,
    FeedbackCreate,
    FeedbackResponse,
    FeedbackUpdate,
    NotificationItem,
    NotificationResponse,
)
from .admin import (
    AdminStatsResponse,
    AdminActivityItem,
    AdminActivityResponse,
    AdminUserItem,
    AdminUsersResponse,
    AdminModelItem,
    AdminModelsResponse,
    AdminFeedbackItem,
    AdminFeedbackResponse,
    AdminChartDataPoint,
    AdminChartResponse,
)

__all__ = [
    "MediaType",
    "DetectionVerdict",
    "UserRole",
    "FeedbackStatus",
    "APIError",
    "ErrorResponse",
    "SuccessResponse",
    "PaginationParams",
    "DetectionRequest",
    "DetectionResult",
    "DetectionHistoryItem",
    "DetectionHistoryResponse",
    "DetectionAnalytics",
    "UserPublic",
    "UserUpdate",
    "UserStatistics",
    "UserSettings",
    "UserSettingsUpdate",
    "UserAnalyticsOverview",
    "ChartData",
    "FeedbackCreate",
    "FeedbackResponse",
    "FeedbackUpdate",
    "NotificationItem",
    "NotificationResponse",
    "AdminStatsResponse",
    "AdminActivityItem",
    "AdminActivityResponse",
    "AdminUserItem",
    "AdminUsersResponse",
    "AdminModelItem",
    "AdminModelsResponse",
    "AdminFeedbackItem",
    "AdminFeedbackResponse",
    "AdminChartDataPoint",
    "AdminChartResponse",
]
